title: Victor Landi
logo: /assets/img/viewprofileimage.jpg

description: 
Table of Contents:
Self Assessment
Code Review
Artifact One - Software Design and Engineering
Artifact Two - Algorithms and Data Structures
Artifact Three - Databases

#show_downloads: true
theme: jekyll-theme-Minimal
